// Carta de Casa Federico. Fuente: carta oficial 2025 (casafederico.es/descargaspdf/dishes2025casafederico.pdf).
// Cada plato: v = valencià, e = castellano, n = english, d = descripción opcional {v,e,n}, p = precio (número o 'S/M').
// El inglés corrige los errores de traducción automática de la carta impresa («Navy tapes», «Pout balls», etc.).

export const secciones = [
  {
    id: 'tapes-marina', v: 'Tapes típiques de la Marina', e: 'Tapas típicas de la Marina', n: 'Marina Alta tapas',
    platos: [
      { v: 'Torrat', e: 'Torrat', n: 'Torrat', d: { v: 'Pebre i albergínia rostits a la brasa', e: 'Pimiento y berenjena asados a la brasa', n: 'Flame-roasted pepper and aubergine' }, p: 8.5 },
      { v: 'Tomacat', e: 'Tomacat', n: 'Tomacat', d: { v: 'Pebre, albergínia, tomaca i saladures', e: 'Pimiento, berenjena, tomate y salazones', n: 'Pepper, aubergine, tomato and salt-cured fish' }, p: 9 },
      { v: 'Bull amb ceba', e: 'Bull con cebolla', n: 'Bull with onion', d: { v: 'Bull de tonyina', e: 'Estómago de atún, plato de la costa', n: 'Cured tuna stomach, a coastal classic' }, p: 9 },
      { v: 'Gambeta amb bleda', e: 'Camarones con acelgas', n: 'Small shrimp with chard', p: 8 },
      { v: 'Polp guisat', e: 'Pulpo guisado', n: 'Stewed octopus', p: 10.5 },
      { v: 'Xones', e: 'Caracoles', n: 'Snails', p: 9.5 },
      { v: 'Manetes de porc', e: 'Manitas de cerdo', n: "Pig's trotters", p: 11.5 },
      { v: 'Pilotes de putxero (unitat)', e: 'Pelotas de puchero (unidad)', n: 'Stew meatball (each)', p: 5 },
      { v: 'Figatells (unitat)', e: 'Figatells (unidad)', n: 'Figatell (each)', d: { v: 'Xicoteta hamburguesa de la terra', e: 'Pequeña hamburguesa tradicional', n: 'Small traditional pork patty' }, p: 3.75 },
      { v: 'Mandonguilles', e: 'Albóndigas', n: 'Meatballs', p: 7 },
      { v: 'Croquetes de bacallar o pernil', e: 'Croquetas de bacalao o jamón', n: 'Salt cod or ham croquettes', p: 10 },
      { v: 'Coques de dacsa (unitat)', e: 'Cocas de maíz (unidad)', n: 'Corn flatbread (each)', d: { v: 'Torrat, tomacat, gamba amb bleda o tonyina', e: 'Torrat, tomacat, camarón con acelgas o atún', n: 'Torrat, tomacat, shrimp with chard or tuna' }, p: 4 },
      { v: 'Coca de dacsa completa (unitat)', e: 'Coca de maíz completa (unidad)', n: 'Corn flatbread "completa" (each)', d: { v: 'Tomaca, tonyina, ou i anxova', e: 'Tomate, atún, huevo y anchoa', n: 'Tomato, tuna, egg and anchovy' }, p: 4.5 },
      { v: 'Verdura a la planxa', e: 'Verdura a la plancha', n: 'Grilled vegetables', p: 12 },
      { v: 'Pernil ibèric', e: 'Jamón ibérico', n: 'Iberian ham', p: 19 },
      { v: 'Formatge manxego', e: 'Queso manchego', n: 'Manchego cheese', p: 10 },
    ],
  },
  {
    id: 'salat-sec', v: 'Salat i sec', e: 'Salado y seco', n: 'Salt-cured & dried',
    platos: [
      { v: 'Polp sec', e: 'Pulpo seco', n: 'Sun-dried octopus', p: 19 },
      { v: 'Capellans o mussola', e: 'Capellanes o cazón seco', n: 'Dried capellans or dogfish', p: 9.5 },
      { v: 'Anxova (unitat)', e: 'Anchoa (unidad)', n: 'Anchovy (each)', p: 3.1 },
      { v: 'Moixama', e: 'Mojama', n: 'Salt-cured tuna loin', p: 18 },
      { v: 'Saladura de la Marina', e: 'Salazones de la Marina', n: 'Marina salt-cured fish platter', p: 18 },
      { v: 'Ganya de bacallar', e: 'Cortezas de bacalao fritas', n: 'Fried salt cod skin', p: 8.5 },
      { v: 'Bacallar amb fons de tomaca', e: 'Bacalao con fondo de tomate', n: 'Salt cod with grated tomato', p: 14.5 },
      { v: 'Aladroc en vinagre', e: 'Boquerones en vinagre', n: 'Anchovies in vinegar', p: 8.5 },
    ],
  },
  {
    id: 'tapes-peix', v: 'Tapes de peix', e: 'Tapas de pescado', n: 'Fish tapas',
    platos: [
      { v: 'Sepionet a la planxa', e: 'Sepionet a la plancha', n: 'Grilled baby cuttlefish', p: 18 },
      { v: 'Tellines', e: 'Tellinas', n: 'Tellina clams', p: 16 },
      { v: 'Fetge de rap', e: 'Hígado de rape', n: 'Monkfish liver', p: 9.5 },
      { v: 'Calamar a la planxa', e: 'Calamar a la plancha', n: 'Grilled squid', p: 16 },
      { v: 'Sèpia', e: 'Sepia', n: 'Cuttlefish', p: 11.5 },
      { v: 'Gambeta de Dénia', e: 'Gambita de Dénia', n: 'Small Dénia shrimp', p: 17 },
      { v: 'Clotxineta del Mediterrani al vapor', e: 'Mejillón del Mediterráneo al vapor', n: 'Steamed Mediterranean mussels', p: 9.5 },
      { v: 'Clòtxines al vapor', e: 'Mejillones al vapor', n: 'Steamed mussels', p: 9.5 },
      { v: 'Polp a la gallega', e: 'Pulpo a la gallega', n: 'Galician-style octopus', p: 17 },
      { v: 'Gambeta saltejada amb allets', e: 'Gambita salteada con ajitos', n: 'Shrimp sautéed with young garlic', p: 17 },
      { v: 'Cigaletes saltejades amb allets', e: 'Cigalitas salteadas con ajitos', n: 'Small langoustines with young garlic', p: 15 },
      { v: 'Fritura de peix de la badia', e: 'Pescadito frito de la bahía', n: 'Fried fish from the bay', p: 15 },
      { v: 'Calamars a la romana', e: 'Calamares a la romana', n: 'Battered squid rings', p: 13 },
      { v: "Calamars a l'andalusa", e: 'Calamares a la andaluza', n: 'Andalusian-style fried squid', p: 15 },
      { v: 'Calamaret arrebossat', e: 'Chipirones rebozados', n: 'Fried baby squid', p: 16 },
      { v: 'Aladroc arrebossat', e: 'Boquerones rebozados', n: 'Fried anchovies', p: 11 },
      { v: 'Ostres', e: 'Ostras', n: 'Oysters', p: 4.5 },
      { v: 'Pa sense gluten', e: 'Pan sin gluten', n: 'Gluten-free bread', p: 2.2 },
      { v: 'Pa amb allioli o tomaca (per persona)', e: 'Pan con allioli o tomate (por persona)', n: 'Bread with allioli or tomato (per person)', p: 1.7 },
    ],
  },
  {
    id: 'ensalades', v: 'Ensalades i verd', e: 'Ensaladas y verde', n: 'Salads & greens',
    platos: [
      { v: 'Mullador', e: 'Mullador', n: 'Mullador', d: { v: "Tomaca madura, bacallar, all i oli d'oliva verge extra", e: 'Tomate maduro, bacalao, ajo y AOVE', n: 'Ripe tomato, salt cod, garlic and extra virgin olive oil' }, p: 11 },
      { v: 'Amanida especial', e: 'Ensalada especial', n: 'Special salad', d: { v: 'Amb ou i tonyina', e: 'Con huevo y atún', n: 'With egg and tuna' }, p: 11 },
      { v: 'Amanida amb torrat i ventresca de tonyina', e: 'Ensalada con escalivada y ventresca de atún', n: 'Roasted vegetable salad with tuna belly', p: 13 },
      { v: 'Espàrrecs amb dues salses', e: 'Espárragos con dos salsas', n: 'Asparagus with two sauces', p: 11 },
      { v: 'Pernil amb meló', e: 'Jamón con melón', n: 'Ham with melon', p: 16 },
      { v: 'Amanida Les Marines', e: 'Ensalada Les Marines', n: 'Les Marines salad', d: { v: 'Amb formatge de cabra', e: 'Con queso de cabra', n: 'With goat cheese' }, p: 13 },
    ],
  },
  {
    id: 'sopes', v: 'Sopes i pastes', e: 'Sopas y pastas', n: 'Soups & pasta',
    platos: [
      { v: 'Consomé', e: 'Consomé', n: 'Meat broth', p: 4.5 },
      { v: 'Crema de verdures', e: 'Crema de verduras', n: 'Cream of vegetables', p: 8 },
      { v: 'Sopa de carn', e: 'Sopa de cocido', n: 'Meat stew soup', p: 8.5 },
      { v: 'Sopa de peix', e: 'Sopa de pescado', n: 'Fish soup', p: 13 },
      { v: 'Gaspatxo andalús', e: 'Gazpacho andaluz', n: 'Andalusian gazpacho', p: 8.5 },
      { v: 'Espaguetis', e: 'Espaguetis', n: 'Spaghetti', p: 7.5 },
    ],
  },
  {
    id: 'peix', v: 'Peix de la badia', e: 'Pescado de la bahía', n: 'Fish from the bay',
    nota: { v: "El peix es podrà preparar a la sal, al forn, a l'espatla o en llandeta, segons disponibilitat.", e: 'El pescado se puede preparar a la sal, al horno, a la espalda o en llandeta, según disponibilidad.', n: 'Fish can be cooked in salt crust, baked, butterflied "a la espalda" or in llandeta, depending on availability.' },
    platos: [
      { v: 'Graellada de peix i marisc (per a 2 persones)', e: 'Parrillada de pescado y marisco (para 2 personas)', n: 'Grilled fish and seafood platter (for 2)', p: 65 },
      { v: '½ Graellada de peix i marisc', e: '½ Parrillada de pescado y marisco', n: '½ Grilled fish and seafood platter', p: 35 },
      { v: 'Peix de la Llotja a la planxa (del dia)', e: 'Pescado de la Lonja a la plancha (del día)', n: "Grilled fish of the day from Dénia's market", d: { v: 'Lluç, moll de roca, pelaia o llobarro', e: 'Pescadilla, salmonete de roca, lenguadina o lubina', n: 'Whiting, red mullet, megrim or sea bass' }, p: 20.5 },
      { v: 'Peix de roca', e: 'Pescado de roca', n: 'Rockfish', d: { v: 'Escorpa, gall de Sant Pere, déntol, mero o llobarro', e: 'Cabracho, San Pedro, dentón, mero o lubina', n: 'Scorpionfish, John Dory, dentex, grouper or sea bass' }, p: 34 },
      { v: 'Emperador a la planxa', e: 'Emperador a la plancha', n: 'Grilled swordfish', p: 18 },
      { v: 'Tonyina a la planxa', e: 'Atún a la plancha', n: 'Grilled tuna', p: 20.5 },
      { v: 'Rap de la badia a la planxa', e: 'Rape de la bahía a la plancha', n: 'Grilled monkfish from the bay', p: 20.5 },
      { v: 'Llenguado a la planxa', e: 'Lenguado a la plancha', n: 'Grilled sole', p: 24.5 },
      { v: 'Llenguado a la meunière', e: 'Lenguado a la meunière', n: 'Sole meunière', p: 26 },
    ],
  },
  {
    id: 'marisc', v: 'Mariscs', e: 'Mariscos', n: 'Shellfish',
    platos: [
      { v: 'Gamba roja de Dénia nº 1, a la planxa o bollida (100 g)', e: 'Gamba roja de Dénia nº 1, a la plancha o hervida (100 g)', n: 'Dénia red prawn nº 1, grilled or boiled (100 g)', p: 'S/M' },
      { v: 'Gamba roja de Dénia nº 2, a la planxa o bollida (100 g)', e: 'Gamba roja de Dénia nº 2, a la plancha o hervida (100 g)', n: 'Dénia red prawn nº 2, grilled or boiled (100 g)', p: 'S/M' },
      { v: 'Cigales a la planxa o bollides (200 g)', e: 'Cigalas a la plancha o hervidas (200 g)', n: 'Langoustines, grilled or boiled (200 g)', p: 22 },
      { v: 'Ostres Gillardeau (unitat)', e: 'Ostras Gillardeau (unidad)', n: 'Gillardeau oysters (each)', p: 4.5 },
      { v: 'Llagosta (100 g)', e: 'Langosta (100 g)', n: 'Spiny lobster (100 g)', p: 14 },
      { v: 'Llamàntol (peça)', e: 'Bogavante (pieza)', n: 'Lobster (whole)', p: 30.5 },
    ],
  },
  {
    id: 'guisos', v: 'Guisos mariners', e: 'Guisos marineros', n: 'Seafood stews',
    nota: { v: 'Mínim dues persones, per encàrrec.', e: 'Mínimo dos personas, por encargo.', n: 'Minimum two people, order in advance.' },
    platos: [
      { v: 'Suquet de peix', e: 'Suquet de pescado', n: 'Fish suquet', p: 25 },
      { v: 'Suquet de rap', e: 'Suquet de rape', n: 'Monkfish suquet', p: 26 },
      { v: 'Allipebre de rap', e: 'All i pebre de rape', n: 'Monkfish all i pebre (garlic & paprika)', p: 26.5 },
      { v: 'Suquet de peix i llamàntol', e: 'Suquet de pescado y bogavante', n: 'Fish and lobster suquet', p: 35 },
      { v: 'Suquet de peix i llagosta', e: 'Suquet de pescado y langosta', n: 'Fish and spiny lobster suquet', p: 48 },
    ],
  },
  {
    id: 'arrossos', v: 'Arrossos secs', e: 'Arroces secos', n: 'Dry rice dishes',
    nota: { v: "Preu per ració. Mínim dues racions. Si es vol més d'un arròs per taula, es farà segons disponibilitat de la cuina.", e: 'Precio por ración. Mínimo dos raciones. Si se quiere más de un arroz por mesa, se hará según disponibilidad de la cocina.', n: 'Price per serving. Minimum two servings. More than one rice per table depends on kitchen availability.' },
    platos: [
      { v: 'Arròs a banda', e: 'Arroz a banda', n: 'Arroz a banda', d: { v: 'El de la Marina, amb fumet de peix', e: 'El de la Marina, con fumet de pescado', n: 'Rice cooked in a rich fish stock' }, p: 15 },
      { v: 'Arròs a la marinera', e: 'Arroz a la marinera', n: 'Seafood rice', p: 17 },
      { v: 'Arròs negre', e: 'Arroz negro', n: 'Black rice (squid ink)', p: 16 },
      { v: 'Arròs del senyoret', e: 'Arroz del señoret', n: 'Señoret rice', d: { v: 'Tot pelat', e: 'Todo el marisco pelado', n: 'All the seafood already peeled' }, p: 17.5 },
      { v: 'Arròs amb llamàntol', e: 'Arroz con bogavante', n: 'Lobster rice', p: 27 },
      { v: 'Arròs mariner amb rajada', e: 'Arroz marinero con raya', n: 'Seafood rice with skate', p: 18 },
      { v: 'Paella valenciana', e: 'Paella valenciana', n: 'Valencian paella', d: { v: 'Pollastre i conill. Opció caragols +0,50', e: 'Pollo y conejo. Opción caracoles +0,50', n: 'Chicken and rabbit. Snails optional +0.50' }, p: 16 },
      { v: "Paella de l'horta, carn i verdures", e: 'Paella de la huerta, carne y verduras', n: 'Garden paella, meat and vegetables', d: { v: 'Caragols opcional +0,50', e: 'Caracoles opcional +0,50', n: 'Snails optional +0.50' }, p: 16 },
      { v: 'Paella de verdura', e: 'Paella de verdura', n: 'Vegetable paella', p: 15 },
      { v: 'Paella de ceba i bacallar', e: 'Paella de cebolla y bacalao', n: 'Onion and salt cod paella', p: 15.5 },
      { v: "Paella d'aladroc i espinacs", e: 'Paella de boquerones y espinacas', n: 'Anchovy and spinach paella', p: 15.5 },
      { v: 'Paella mixta', e: 'Paella mixta', n: 'Mixed paella', p: 18 },
      { v: 'Arròs al forn (per encàrrec)', e: 'Arroz al horno (por encargo)', n: 'Oven-baked rice (order in advance)', p: 15 },
      { v: 'Fideuada', e: 'Fideuá', n: 'Fideuà', d: { v: 'De fideu fi', e: 'De fideo fino', n: 'Thin noodles cooked like a paella' }, p: 17 },
      { v: "Fideuada de bolets i foie d'ànec", e: 'Fideuá de setas y foie de pato', n: 'Fideuà with mushrooms and duck foie', p: 22 },
    ],
  },
  {
    id: 'caldosos', v: 'Arrossos melosos o caldosos', e: 'Arroces melosos y caldosos', n: 'Creamy & brothy rice',
    nota: { v: 'Tots els arrossos es poden preparar secs, melosos o caldosos. Mínim dues racions.', e: 'Todos los arroces se pueden preparar secos, melosos o caldosos. Mínimo dos raciones.', n: 'Every rice can be made dry, creamy or brothy. Minimum two servings.' },
    platos: [
      { v: 'Arròs caldós a la marinera', e: 'Arroz caldoso a la marinera', n: 'Brothy seafood rice', p: 17.5 },
      { v: 'Arròs caldós amb calamar i verdura', e: 'Arroz caldoso con calamar y verdura', n: 'Brothy rice with squid and vegetables', p: 17.5 },
      { v: 'Arròs caldós amb polp i verdura', e: 'Arroz caldoso con pulpo y verdura', n: 'Brothy rice with octopus and vegetables', p: 17.5 },
      { v: 'Arròs caldós amb rap i verdura', e: 'Arroz caldoso con rape y verdura', n: 'Brothy rice with monkfish and vegetables', p: 18 },
      { v: 'Arròs caldós de carn i verdura', e: 'Arroz caldoso de carne y verdura', n: 'Brothy rice with meat and vegetables', p: 16 },
      { v: 'Arròs amb fesols i naps', e: 'Arroz con alubias y nabos', n: 'Rice with beans and turnips', d: { v: 'De temporada i per encàrrec', e: 'De temporada y por encargo', n: 'Seasonal, order in advance' }, p: 16 },
      { v: 'Arròs de putxero amb pilota', e: 'Arroz de puchero con pelota', n: 'Stew rice with meatball', p: 9.5 },
    ],
  },
  {
    id: 'carns', v: 'Carns', e: 'Carnes', n: 'Meat',
    nota: { v: 'Totes les carns es poden preparar amb salsa de rocafort, pebre o bolets (+2,50).', e: 'Todas las carnes se pueden preparar con salsa roquefort, pimienta o setas (+2,50).', n: 'Any meat can come with Roquefort, pepper or mushroom sauce (+2.50).' },
    platos: [
      { v: 'Xulles de xai', e: 'Chuletas de cordero', n: 'Lamb chops', p: 19.5 },
      { v: 'Entrecot de vedella', e: 'Entrecot de ternera', n: 'Beef entrecôte', p: 19 },
      { v: 'Mitjana de vaca madura, 45 dies (aprox. 1 kg)', e: 'Chuletón de vaca madurada 45 días (aprox. 1 kg)', n: '45-day aged beef rib steak (approx. 1 kg)', p: 33 },
      { v: 'Rellom de vedella a la planxa', e: 'Solomillo de ternera a la plancha', n: 'Grilled beef tenderloin', p: 24 },
      { v: 'Rellom de vedella amb foie', e: 'Solomillo de ternera con foie', n: 'Beef tenderloin with foie', p: 28 },
      { v: 'Cordon bleu', e: 'Cordon bleu', n: 'Cordon bleu', p: 13 },
      { v: 'Escalopa', e: 'Escalope', n: 'Escalope', p: 13 },
      { v: 'Pollastre arrebossat', e: 'Pollo empanado', n: 'Breaded chicken', p: 10.5 },
    ],
  },
  {
    id: 'postres', v: 'Postres de la casa', e: 'Postres caseros', n: 'Homemade desserts',
    platos: [
      { v: 'Pasta fullada amb xocolate calent', e: 'Hojaldre con chocolate caliente', n: 'Puff pastry with hot chocolate', p: 8 },
      { v: "Gelat d'ametla", e: 'Helado de almendra', n: 'Almond ice cream', p: 7 },
      { v: 'Flam de carabassa', e: 'Flan de calabaza', n: 'Pumpkin flan', p: 6.5 },
      { v: 'Tiramisú', e: 'Tiramisú', n: 'Tiramisu', p: 7.5 },
      { v: "Flam d'ou", e: 'Flan de huevo', n: 'Egg flan', p: 4.5 },
      { v: 'Flam amb nata', e: 'Flan con nata', n: 'Egg flan with cream', p: 5 },
      { v: "Flam d'avellana", e: 'Flan de avellana', n: 'Hazelnut flan', p: 6 },
      { v: 'Flam de café', e: 'Flan de café', n: 'Coffee flan', p: 6 },
      { v: 'Crema catalana', e: 'Crema catalana', n: 'Crema catalana', p: 5 },
      { v: 'Flamet', e: 'Tocinillo de cielo', n: 'Tocinillo de cielo (egg-yolk custard)', p: 6.5 },
      { v: 'Mousse de xocolate', e: 'Mousse de chocolate', n: 'Chocolate mousse', p: 6.5 },
      { v: 'Natilles', e: 'Natillas', n: 'Custard', p: 4.5 },
      { v: 'Pastís de formatge', e: 'Tarta de queso', n: 'Cheesecake', p: 6.5 },
      { v: 'Pastís al whisky', e: 'Tarta al whisky', n: 'Whisky cake', p: 7 },
      { v: 'Nous amb nata', e: 'Nueces con nata', n: 'Walnuts with cream', p: 6 },
      { v: 'Maduixes amb nata (temporada)', e: 'Fresas con nata (temporada)', n: 'Strawberries and cream (seasonal)', p: 6.5 },
      { v: 'Sorbet de llima al cava', e: 'Sorbete de limón al cava', n: 'Lemon sorbet with cava', p: 6.5 },
      { v: 'Sorbet de mandarina', e: 'Sorbete de mandarina', n: 'Mandarin sorbet', p: 6.5 },
      { v: 'Sorbet de mango', e: 'Sorbete de mango', n: 'Mango sorbet', p: 6.5 },
      { v: 'Formatge amb codony', e: 'Queso con membrillo', n: 'Cheese with quince', p: 6 },
      { v: 'Formatge (postre)', e: 'Queso (postre)', n: 'Cheese (dessert)', p: 7.5 },
      { v: 'Pinya natural', e: 'Piña natural', n: 'Fresh pineapple', p: 6.5 },
      { v: 'Fruita del temps', e: 'Fruta del tiempo', n: 'Seasonal fruit', p: 6 },
      { v: 'Bola de gelat (unitat)', e: 'Bola de helado (unidad)', n: 'Scoop of ice cream', p: 2.9 },
    ],
  },
];
